//ejemplos
export const productosData = {
  graymayas: [
    {
      id: 1,
      nombre: "Sudadera Negra Premium",
      descripcion: "Sudadera con cierre de alta calidad",
      precio: 899,
      stock: true,
      imagen: "/black-premium-hoodie-with-zipper.jpg",
      categoria: "sudaderas-cierre",
    },
    {
      id: 2,
      nombre: "Sudadera Cerrada Classic",
      descripcion: "Diseño minimalista y cómodo",
      precio: 799,
      stock: true,
      imagen: "/black-pullover-hoodie-minimal.jpg",
      categoria: "sudaderas-cerradas",
    },
    {
      id: 3,
      nombre: "Playera Graymaya Edition",
      descripcion: "Edición limitada con logo bordado",
      precio: 499,
      stock: false,
      imagen: "/black-t-shirt-with-embroidered-logo.jpg",
      categoria: "playeras",
    },
    {
      id: 4,
      nombre: "Sudadera Oversized",
      descripcion: "Corte holgado estilo urbano",
      precio: 949,
      stock: true,
      imagen: "/oversized-black-hoodie-streetwear.png",
      categoria: "sudaderas-cerradas",
    },
    {
      id: 5,
      nombre: "Playera Long Fit",
      descripcion: "Corte largo para look moderno",
      precio: 549,
      stock: true,
      imagen: "/long-fit-black-t-shirt.jpg",
      categoria: "playeras",
    },
    {
      id: 6,
      nombre: "Sudadera Tech Fabric",
      descripcion: "Tela técnica de alto rendimiento",
      precio: 1099,
      stock: true,
      imagen: "/technical-fabric-black-hoodie.jpg",
      categoria: "sudaderas-cierre",
    },
  ],
  basicos: [
    {
      id: 7,
      nombre: "Camiseta Básica Negra",
      descripcion: "Esencial para cualquier guardarropa",
      precio: 299,
      stock: true,
      imagen: "/basic-black-t-shirt.jpg",
      categoria: "camisetas",
    },
    {
      id: 8,
      nombre: "Camiseta Blanca Premium",
      descripcion: "Algodón 100% de alta calidad",
      precio: 349,
      stock: true,
      imagen: "/premium-white-t-shirt.png",
      categoria: "camisetas",
    },
    {
      id: 9,
      nombre: "Pantalón Cargo Negro",
      descripcion: "Múltiples bolsillos funcionales",
      precio: 699,
      stock: true,
      imagen: "/black-cargo-pants.png",
      categoria: "pantalones",
    },
    {
      id: 10,
      nombre: "Camiseta Gris Melange",
      descripcion: "Tela suave y transpirable",
      precio: 299,
      stock: true,
      imagen: "/gray-melange-t-shirt.jpg",
      categoria: "camisetas",
    },
    {
      id: 11,
      nombre: "Pantalón Jogger",
      descripcion: "Comodidad y estilo urbano",
      precio: 649,
      stock: false,
      imagen: "/black-jogger-pants.jpg",
      categoria: "pantalones",
    },
    {
      id: 12,
      nombre: "Pack 3 Camisetas",
      descripcion: "Negro, blanco y gris",
      precio: 799,
      stock: true,
      imagen: "/3-pack-basic-t-shirts.jpg",
      categoria: "camisetas",
    },
  ],
  accesorios: [
    {
      id: 13,
      nombre: "Gorra Snapback",
      descripcion: "Logo bordado frontal",
      precio: 399,
      stock: true,
      imagen: "/black-snapback-cap.png",
      categoria: "gorras",
    },
    {
      id: 14,
      nombre: "Mochila Urban",
      descripcion: "Compartimento para laptop",
      precio: 899,
      stock: true,
      imagen: "/black-urban-backpack.jpg",
      categoria: "mochilas",
    },
    {
      id: 15,
      nombre: "Gorra Dad Hat",
      descripcion: "Estilo clásico ajustable",
      precio: 349,
      stock: true,
      imagen: "/black-dad-hat.jpg",
      categoria: "gorras",
    },
    {
      id: 16,
      nombre: "Calcetines Pack 5",
      descripcion: "Algodón premium",
      precio: 249,
      stock: true,
      imagen: "/black-socks-pack.jpg",
      categoria: "otros",
    },
    {
      id: 17,
      nombre: "Mochila Mini",
      descripcion: "Perfecta para lo esencial",
      precio: 599,
      stock: false,
      imagen: "/black-mini-backpack.jpg",
      categoria: "mochilas",
    },
    {
      id: 18,
      nombre: "Gorra Beanie",
      descripcion: "Tejido suave para invierno",
      precio: 299,
      stock: true,
      imagen: "/black-beanie-hat.jpg",
      categoria: "gorras",
    },
  ],
  colaboraciones: [
    {
      id: 19,
      nombre: "Collab Artist Series 01",
      descripcion: "Diseño exclusivo edición limitada",
      precio: 1299,
      stock: true,
      imagen: "/limited-edition-artist-collaboration-hoodie.jpg",
      categoria: "disponibles",
    },
    {
      id: 20,
      nombre: "Collab Street Edition",
      descripcion: "Colaboración con artista urbano",
      precio: 1499,
      stock: false,
      imagen: "/street-art-collaboration-t-shirt.jpg",
      categoria: "disponibles",
    },
    {
      id: 21,
      nombre: "Collab Future Drop",
      descripcion: "Próximamente - Reserva ya",
      precio: 1399,
      stock: false,
      imagen: "/placeholder.svg?height=300&width=300",
      categoria: "proximamente",
    },
    {
      id: 22,
      nombre: "Collab Designer Series",
      descripcion: "Colaboración con diseñador emergente",
      precio: 1599,
      stock: true,
      imagen: "/placeholder.svg?height=300&width=300",
      categoria: "disponibles",
    },
    {
      id: 23,
      nombre: "Collab Music Edition",
      descripcion: "Inspirado en la cultura musical",
      precio: 1199,
      stock: true,
      imagen: "/placeholder.svg?height=300&width=300",
      categoria: "disponibles",
    },
    {
      id: 24,
      nombre: "Collab Next Gen",
      descripcion: "Próximamente - Suscríbete",
      precio: 1499,
      stock: false,
      imagen: "/placeholder.svg?height=300&width=300",
      categoria: "proximamente",
    },
  ],
};
